package miceta.game.core.util;

/**
 * Created by ewe on 2/2/18.
 */
public enum ScreenName {
    CONCRETE_TUTORIAL, ORGANIC_HELP,
    GAME_STEPS, GAME_KNOCK, GAME_INGREDIENTS,GAME_MIXING, GAME_MUSIC, GAME_GREETING,
    NONE, EXIT, RESTART, LAST_SCREEN,
    FINAL_MM1, INTRO_MM2,
    GAME_HOLES, GAME_WINGS, GAME_BIRD, GAME_NUMERUS,
    FINAL_MM2
}
